apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f28itpbfk-go 
  janus-idp.io/tekton: f28itpbfk-go
  backstage.io/kubernetes-id: f28itpbfk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f28itpbfk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml