apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f28itpbfk-go-gitops
  description: This is GitOps manifest for f28itpbfk-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=f28itpbfk-go
    backstage.io/kubernetes-id: f28itpbfk-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: f28itpbfk-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f28itpbfk-go
