apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f28itpbfk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f28itpbfk-go 
  name: f28itpbfk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: f28itpbfk-go 
